Add 'provenance.submission_date' and '.update_date' fields (#45)
DataBiosphere/hca-metadata-api pull request #46
Opened 2021-04-21 23:36 UTC by danielsotirhos

2021-04-22 16:20 UTC, danielsotirhos commented
Note that according to the https://schema.humancellatlas.org/system/1.1.0/provenance schema, `submission_date` is a required field and `update_date` is optional.

2021-04-22 18:28 UTC, jessebrennan approved these changes

2021-04-22 18:28 UTC, jessebrennan commented on test/test.py
> +            None: 1,
Assuming that this missing one is because of the deletion up above, right?

2021-04-22 18:35 UTC, dsotirho-ucsc commented on test/test.py
> +            None: 1,
Yes, I removed the `update_date` field from one of the metadata files of the canned bundle to make sure the case of the optional field being not present was covered.

2021-04-23 19:11 UTC, hannes-ucsc requested changes

2021-04-23 19:11 UTC, hannes-ucsc commented on test/test.py
> +        self.assertEqual(submitter_id_counts, {
Expected should be first argument. And why do you inline one argument but extract the other into a variable? Both are relatively long expressions.

2021-04-23 19:11 UTC, hannes-ucsc commented on test/test.py
> +            '2019-09-20T08:29:52.232Z': 1,
Might want to comprehend over this since only the millis are different.

2021-04-23 19:11 UTC, hannes-ucsc commented on test/test.py
> +            '2019-09-20T08:38:58.165Z': 2,
This one might not be worth a comprehension.

2021-04-23 19:11 UTC, hannes-ucsc commented on src/humancellatlas/data/metadata/api.py
> +        self.update_date = lookup(provenance, 'update_date', 'updateDate', default=None)
These attributes should be declared at the top.

2021-04-27 00:19 UTC, hannes-ucsc approved these changes

2021-04-27 00:25 UTC, merged