Add project.publications.official_hca_publication and doi (DataBiosphere/azul#3502)
DataBiosphere/hca-metadata-api pull request #60
Opened 2021-10-07 22:57 UTC by danielsotirhos

https://github.com/DataBiosphere/azul/issues/3502

2021-10-13 18:14 UTC, jessebrennan approved these changes

2021-10-26 19:53 UTC, hannes-ucsc requested changes

2021-10-26 19:53 UTC, hannes-ucsc commented on src/humancellatlas/data/metadata/api.py
> +    official_hca_publication: Optional[bool]
```suggestion
    official_hca: Optional[bool]
```

since we stripped that word from the other property names as well.

2021-10-29 18:01 UTC, hannes-ucsc approved these changes

2021-10-29 18:08 UTC, hannes-ucsc commented
@danielsotirhos, please merge and create a new release (merge to develop to main, create release label, create release, prepare next release on develop).

2021-11-01 21:05 UTC, merged