Create release guide (#59)
DataBiosphere/hca-metadata-api pull request #63
Opened 2021-12-13 17:27 UTC by danielsotirhos

https://github.com/databiosphere/hca-metadata-api/issues/59

2021-12-13 20:14 UTC, achave11 approved these changes
LGTM!

2022-01-24 19:27 UTC, hannes-ucsc requested changes

2022-01-24 19:27 UTC, hannes-ucsc commented on README.md
> +## Release Guide
```suggestion
## Release guide
```

Precedent.

2022-01-24 19:27 UTC, hannes-ucsc commented on README.md
> +### Step 1: Merge `develop` Into `main`
Nested numbered list would be less verbose and wouldn't clutter the TOC.

2022-01-24 19:27 UTC, hannes-ucsc commented on README.md
> +- Resolve conflicts in setup.py, promote to the higher version.
Empty lines between paragraphs. A heading is a special paragraph.

2022-01-27 19:25 UTC, hannes-ucsc requested changes

2022-01-27 19:25 UTC, hannes-ucsc commented on README.md
> +   - Resolve conflicts in setup.py, promote to the higher version.
```suggestion
   - Resolve conflicts in `setup.py`, promote to the higher version.
```

2022-01-27 19:25 UTC, hannes-ucsc commented on README.md
> +   - Resolve conflicts in setup.py, promote to the higher version.
Ideally, empty lines around 2nd level bullet items

2022-01-27 19:25 UTC, hannes-ucsc commented on README.md
> +   - GitHub -> Releases -> Draft a new release
```suggestion
   - On the GitHub epository home page click *Releases* — *Draft a new release*
```

2022-01-27 19:25 UTC, hannes-ucsc commented on README.md
> +   - GitHub -> Releases -> Draft a new release
That's an mdash and italics for UI elements. Here and where applicable.

2022-02-04 19:54 UTC, hannes-ucsc requested changes
The build isn't green. Probably because some interaction with #66 which I added as a blocker. Please hold this warm.

2022-02-26 02:32 UTC, hannes-ucsc approved these changes

2022-02-26 02:40 UTC, merged